FROM node:16.15.1-alpine

ARG VITE_JWT_SECRET
ARG VITE_SCRAPE_TOKEN
ARG VITE_DATABASE_URL
ARG VITE_FILES_PATH
ARG VITE_CRONJOBORG_TOKEN

ENV VITE_JWT_SECRET=$VITE_JWT_SECRET
ENV VITE_SCRAPE_TOKEN=$VITE_SCRAPE_TOKEN
ENV VITE_DATABASE_URL=$VITE_DATABASE_URL
ENV VITE_FILES_PATH=$VITE_FILES_PATH
ENV VITE_CRONJOBORG_TOKEN=$VITE_CRONJOBORG_TOKEN

COPY . /tmp/app
WORKDIR /tmp/app
RUN npm install
RUN npx prisma generate
RUN npm run build
CMD ["node", "build"]
