name: Docker Images CI
on:
  push:
    branches: [ "main" ]
jobs:
  build-webapp:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webapp
    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_ACCESSTOKEN: ${{secrets.DOCKER_ACCESSTOKEN}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESSTOKEN
      - name: test
        run: ls -la
      - name: Build the Scrapi Webapp Image
        run: docker build . --file Dockerfile --tag scrapi-webapp:$(date +%s)
