name: Docker Images CI
on:
  push:
    branches: ["main"]
jobs:
  build-webapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_ACCESSTOKEN: ${{secrets.DOCKER_ACCESSTOKEN}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESSTOKEN
      - name: Build the Scrapi Webapp Image
        run: docker build . --file webapp/Dockerfile --tag ${{secrets.DOCKER_USERNAME}}/scrapi-webapp:latest
      - name: Docker Push
        run: docker push ${{secrets.DOCKER_USERNAME}}/scrapi-webapp:latest
  build-daemon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_ACCESSTOKEN: ${{secrets.DOCKER_ACCESSTOKEN}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESSTOKEN
      - name: Build the Scrapi Daemon Image
        run: docker build . --file daemon/Dockerfile --tag ${{secrets.DOCKER_USERNAME}}/scrapi-daemon:latest
      - name: Docker Push
        run: docker push ${{secrets.DOCKER_USERNAME}}/scrapi-daemon:latest
